services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    user: '1000:1000'
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - '8088:80'
    volumes:
      - ${APP_DATA_DIR}//vw-data:/data
    environment:
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
